// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrackingAppReact.Data;

#nullable disable

namespace TrackingAppReact.Migrations
{
    [DbContext(typeof(TrackingDBContext))]
    [Migration("20230331160319_migration310323")]
    partial class migration310323
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TrackingAppReact.Models.Inbox", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Delay")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DispatchNote")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Handling")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID");

                    b.ToTable("Inbox");
                });

            modelBuilder.Entity("TrackingAppReact.Models.OrderChange", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("ContainerID")
                        .HasColumnType("int");

                    b.Property<string>("TrackingNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID");

                    b.ToTable("OrderChange");
                });
#pragma warning restore 612, 618
        }
    }
}
